#!/usr/bin/env zsh

#### xdg
export XDG_CONFIG_HOME="$HOME/.config"
[[ -d "$XDG_CONFIG_HOME" ]] || mkdir -p "$XDG_CONFIG_HOME"
### Cache
export XDG_CACHE_HOME="$HOME/.cache"
[[ -d "$XDG_CACHE_HOME" ]] || mkdir -p "$XDG_CACHE_HOME"
### Data
export XDG_DATA_DIRS="$HOME/.local/share"
[[ -d "$XDG_DATA_DIRS" ]] || mkdir -p "$XDG_DATA_DIRS"
### Cache
export XDG_STATE_HOME="$HOME/.local/state"
[[ -d "$XDG_STATE_HOME" ]] || mkdir -p "$XDG_STATE_HOME"

#### zsh
export ZDOTDIR="$HOME/.config/zsh"
[[ -d "$ZDOTDIR" ]] || mkdir -p "$ZDOTDIR"
### Cache
export ZSH_CACHE_DIR="$HOME/.cache/zsh"
[[ -d "$CACHEDIR" ]] || mkdir -p "$CACHEDIR"
##s plugins
export ZSH_PLUGINS="$HOME/.config/zsh/plugins"
[[ -d "$ZSH_PLUGINS" ]] || mkdir -p "$ZSH_PLUGINS"
### Completions
export ZSH_COMPLETIONS="$HOME/.cache/zsh/completions"
[[ -d "$ZSH_COMPLETIONS" ]] || mkdir -p "$ZSH_COMPLETIONS"

### Create cache and completions dir and add to $fpath ###
fpath=($HOME/.cache/zsh/completions $fpath)
_comp_options+=(globdots)

# Editor + Others
export EDITOR=/usr/bin/nvim
export PAGER="/bin/sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
export MANPAGER="/bin/sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
export VISUAL=/usr/bin/nvim
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"     

export BROWSER=/usr/bin/vivaldi

# starship config
#export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

### Path ###
export PATH="/usr/bin:/bin:/usr/sbin:$HOME/.local/sbin:/sbin:$HOME/.local/bin:$HOME/.local/share:$HOME/.cargo/bin:$HOME/.cargo/env:$PATH"

### TERMINAL ###
export TERM="xterm-256color"
export COLORTERM="truecolor"
DISABLE_LS_COLORS="true"

### LANG ###
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# misc
export WORDCHARS='~!#$%^&*(){}[]<>?.+;'  
export GPG_TTY="$(tty)"

# ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# bat
export BAT_THEME="Dracula"

# p10k
source "$ZDOTDIR/themes/powerlevel10k/powerlevel10k.plugin.zsh"
