#!/usr/bin/env zsh

### ZSH SOURCES ###
typeset -ga sources
for file in "${ZDOTDIR}/include/aliases.zsh" \
            "${ZDOTDIR}/include/bindkeys.zsh \
            "${ZDOTDIR}/include/completion.zsh" \
            "${ZDOTDIR}/include/functions.zsh" \
            "${ZDOTDIR}/include/less.zsh" \
            "${ZDOTDIR}/include/setopt.zsh" \
            "${ZSH_PLUGINS}/auto-ls-zsh/auto-ls.zsh" 
    [ -s "${file}" ] && source "${file}"
done

### Added by ZI's Installer ###
if [[ ! -f $HOME/.zi/bin/zi.zsh ]] then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}ZI%F{220} Initiative Plugin Manager (%F{33}z-shell/zi%F{220})…%f"
    command mkdir -p $HOME/.zsh/zi && command g-rwX "$HOME/.zi"
    command git clone https://github.com/z-shell/zi "$HOME/.zsh/zi/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
source "${ZDOTDIR}/zi/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi
### End of ZI's installer chunk

### Prompt ###
zi light @romkatv

# ohmyzsh libraries
zi snippet OMZL::compfix.zsh 
zi snippet OMZL::completion.zsh 
zi snippet OMZL::functions.zsh
zi snippet OMZL::correction.zsh 
zi snippet OMZL::git.zsh
zi snippet OMZL::termsupport.zsh 
zi snippet OMZL::theme-and-appearance.ZSH

# ohmyzsh plugins
zi snippet OMZP::colored-man-pages
zi snippet OMZP::command-not-found
zi snippet OMZP::direnv
zi snippet OMZP::docker
zi snippet OMZP::docker-compose
zi snippet OMZP::extract
zi snippet OMZP::fzf
zi snippet OMZP::git
zi snippet OMZP::ripgrep
zi snippet OMZP::rust

### Programs 
zcomet trigger bat sharkdp/bat
zcomet trigger bottom bt ClementTsang/bottom
zcomet trigger dt dandavision/delta
zcomet trigger du bootandy/dust
zcomet trigger ll ogham/exa   
zcomet trigger fd sharkdp/fd
zcomet trigger l Peltoche/lsd
zcomet trigger ps dalance/procs
zcomet trigger rg BurntSushi/ripgrep
zcomet trigger battop bt svartalf/rust-battop
zcomet trigger sd chmln/sd

# completions
zi ice as"completion"
zi snippet OMZP::docker/_docker

zi ice as"completion"
zi snippet OMZP::fd/_fd








# History environment variables
HISTFILE=${ZDOTDIR}/zhistory
HISTSIZE=120000  
SAVEHIST=100000

# add a config file for ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

### make sure zsh-autosuggestions does't interfere ###
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(expand-or-complete bracketed-paste accept-line push-line-or-edit)

# Cargo 
source $HOME/.cargo/env

# install neofetch-btw ###

# LS_COLORS (vivid)
export LS_COLORS="$(vivid generate snazzy)"

# cod
source <(cod init $$ zsh)

