#!/usr/bin/env zsh

### ZSH SOURCES ###
typeset -ga sources
for file in "${ZDOTDIR}/core/aliases.zsh" \
            "${ZDOTDIR}/core/bindkeys.zsh" \
            "${ZDOTDIR}/core/completion.zsh" \
            "${ZDOTDIR}/core/functions.zsh" \
            "${ZDOTDIR}/core/less.zsh" \
            "${ZDOTDIR}/core/setopt.zsh" \
    [[ -f "${file}" ]] && source "${file}"
done

=1

# Load plugins.
source $ZDOTDIR/themes/powerlevel10k/powerlevel10k.zsh-theme
source $HOME/.p10k.zsh

# Cargo 
source $HOME/.cargo/env

# install neofetch-btw ###

# LS_COLORS (vivid)
export LS_COLORS="$(vivid generate dracula)"

