#!/usr/bin/env zsh

### ZSH SOURCES ###
typeset -ga sources
for file in "${ZDOTDIR}/include/aliases.zsh" \
            "${ZDOTDIR}/include/bindkeys.zsh \
            "${ZDOTDIR}/include/completion.zsh" \
            "${ZDOTDIR}/include/functions.zsh" \
            "${ZDOTDIR}/include/less.zsh" \
            "${ZDOTDIR}/include/setopt.zsh" \
            "${ZDOTDIR}/include/less.zsh" \
            "${ZSH_PLUGINS}/find-the-command/ftc.zsh" \
            "${ZSH_PLUGINS}/zsh-defer/zsh-defer.plugin.zsh" \
            "${ZSH_PLUGINS}/auto-ls-zsh/auto-ls.zsh" 
    [ -s "${file}" ] && source "${file}"
done

### Added by ZI's Installer ###
if [[ ! -f $HOME/.zi/bin/zi.zsh ]] then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}ZI%F{220} Initiative Plugin Manager (%F{33}z-shell/zi%F{220})…%f"
    command mkdir -p $HOME/.zsh/zi && command g-rwX "$HOME/.zi"
    command git clone https://github.com/z-shell/zi "$HOME/.zsh/zi/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
source "${ZDOTDIR}/zi/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi
### End of ZI's installer chunk

### Prompt ###
zi light @romkatv

# ohmyzsh plugins
zcomet load ohmyzsh lib compfix.zsh 
zcomet load ohmyzsh lib completion.zsh 
zcomet load ohmyzsh lib correction.zsh 
zcomet load ohmyzsh lib functions.zsh
zcomet load ohmyzsh lib git.zsh
zcomet load ohmyzsh lib termsupport.zsh 
zcomet load ohmyzsh lib theme-and-appearance

# omzp snippets
zcomet load ohmyzsh plugins/colored-man-pages
zcomet load ohmyzsh plugins/command-not-found
zcomet load ohmyzsh plugins/direnv
zcomet load ohmyzsh plugins/docker
zcomet load ohmyzsh plugins/docker-compose
zcomet load ohmyzsh plugins/extract
zcomet load ohmyzsh plugins/fzf
zcomet load ohmyzsh plugins/ripgrep
zcomet load ohmyzsh plugins/rust

### Programs 
zcomet trigger bat sharkdp/bat
zcomet trigger bottom bt ClementTsang/bottom
zcomet trigger dt dandavision/delta
zcomet trigger du bootandy/dust
zcomet trigger ll ogham/exa   
zcomet trigger fd sharkdp/fd
zcomet trigger l Peltoche/lsd
zcomet trigger ps dalance/procs
zcomet trigger rg BurntSushi/ripgrep
zcomet trigger battop bt svartalf/rust-battop
zcomet trigger sd chmln/sd


# History environment variables
HISTFILE=${ZDOTDIR}/zhistory
HISTSIZE=120000  
SAVEHIST=100000

# add a config file for ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

### make sure zsh-autosuggestions does't interfere ###
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(expand-or-complete bracketed-paste accept-line push-line-or-edit)

# Cargo 
source $HOME/.cargo/env

# install neofetch-btw ###

# LS_COLORS (vivid)
export LS_COLORS="$(vivid generate snazzy)"

# cod
source <(cod init $$ zsh)

