# must run 'sheldon init --shell zsh'

shell = "zsh" 

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fzf] 
github = "junegunn/fzf" 
use = ["shell/completion.zsh", "shell/key-bindings.zsh"] 

[plugins.docker-completions] 
github = "docker/cli" 
use = ["contrib/completion/zsh/_docker"] 
apply = ["fpath"] 
  
[plugins.zsh-completions] 
github = "zsh-users/zsh-completions" 
apply = ["fpath"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.history-search-multi-word]
github = "zdharma-continuum/history-search-multi-word"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/history-substring-search/history-substring-search.plugin.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
mafredri/zsh-async 
romkatv/powerlevel10k 
junegunn/fzf
sharkdp/fd
sharkdp/bat
eth-p/bat-extras
sharkdp/vivid
zchee/zsh-completions


source $HOME/zsh-znap/.znap.zsh
