#!/usr/bin/env sh

### ROFI ###
# power options
alt + p
        sh ~/.config/rofi/bin/powermenu.sh

# program launcher
alt + f1
        sh ~/.config/rofi/bin/launchpad.sh

# Rofi Network Menu
alt + n
	sh ~/.config/rofi/bin/network.sh

# Rofi Menus/Applets
super + {w,a}
	sh ~/.config/bspwm/rofi/bin/{windows,asroot}


### APPS ###
# Kitty
alt + Return
        kitty

# screenshot
Print
        scrot -b -d 5 '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f $HOME/Pictures/'

# file manager
shift + {f,w,e,m}
    	{thunar,vivaldi,oni2,spotify}

#############
### BSPWM ###
#############
# make sxhkd reload its configuration files:
alt + Escape
    	pkill -USR1 -x sxhkd

# Close App
alt + {_,shift + }q
	bspc node -{c,k}

# kill window
ctrl + alt + Escape
    xkill

# Quit/Restart bspwm
shift + {q,r}
	bspc {quit,wm -r}

# polybar autoclose
super + b
        polybar-msg cmd toggle

##---------- System Keys ----------##

# Take a screenshot
Print
	takeshot --now
	
# Take screenshot in 5 second
alt + Print	
	takeshot --in5

# Take screenshot in 10 second
shift + Print	
	takeshot --in10

# Take screenshot of active window
ctrl + Print
	takeshot --win

# Take screenshot of area
ctrl + alt + Print
	takeshot --area

# Brighness control
XF86MonBrightness{Up,Down}
	brightness{ --inc, --dec}
	
# Volume control
XF86Audio{RaiseVolume,LowerVolume}
	volume{ --inc, --dec}

XF86AudioMute
	volume --toggle

XF86AudioMicMute
	volume --toggle-mic

# Music control
XF86Audio{Next,Prev,Play,Stop}
	mpc {next,prev,toggle,stop}

# Split horizontal, vertical or cancel
super + {h,v,q}
	bspc node -p {east,south,cancel}

# Preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# Fullscreen or Monocle
super + f
#	bspc desktop -l next
    bspc node -t "~"fullscreen

# Toggle beetwen floating & tiled
super + space
    bspc node -t "~"{floating,tiled}

# Pseudo Tiled & tiled mode
super + shift + space
#super + {p,t}
    bspc node -t "~"{pseudo_tiled,tiled}

# Set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# Send the window to another edge of the screen
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# Change focus to next window, including floating window
alt + {_,shift + }Tab
	bspc node -f {next.local,prev.local}

# Switch workspace
ctrl + alt + {Left,Right}
	bspc desktop -f {prev.local,next.local}

# Switch to last opened workspace
super + {Tab,grave}
	bspc {node,desktop} -f last

# Send focused window to another workspace
super + {_,shift + }{1-8}
	bspc {desktop -f,node -d} '^{1-8}'

# Expanding windows
super + control + {Left,Right,Up,Down}
	bspc node -z {left -20 0,right 20 0,top 0 -20,bottom 0 20}
	
## Shrinking windows
super + alt + {Left,Right,Up,Down}
	bspc node -z {left 20 0,right -20 0,top 0 20,bottom 0 -20}
	
## Move floating windows
alt + shift + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


  
