#!/usr/bin/env sh
### ROFI ###
# power options
super + p
	rofi -theme $HOME/.config/rofi/powermenu/full_rounded.rasi

# program launcher
alt + f1
        rofi -no-lazy-grab -show drun -modi drun -show-icons -theme $HOME/.config/rofi/launchers/misc/launchpad.rasi

# colorscheme
super + shift + t
        $HOME/.config/polybar/scripts/style-switch.sh

### APPS ###
# screenshot
super + shift + s
        scrot -b -d 5 '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f /home/tdm/Pictures/'

# terminal emulator
super + Return
	alacritty

# file manager
super + e
	thunar

# web brower
super + w
        vivaldi-stable

### BSPWM ###
# make sxhkd reload its configuratzion files:
super + Escape
	pkill -USR1 -x sxhkd

# restart bspwm
super + shift + r
	bspc wm -r

# close
super + q
	bspc node -c

# kill
super + shift + q
        bspc node -k

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window



# Volume hotkeys
@XF86Audio{Raise,Lower}Volume
	amixer sset Master 2%{+,-}

@XF86AudioMute
	amixer sset Master toggle

# Brightness hotkeys
@XF86MonBrightness{Up,Down}
	xbacklight -{inc,dec} 10
	



### move/resize ###
# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}




### state/flags ###
# set the window state
super + {t,shift + d,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

### focus/swap ###
# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'



### preselect ###
# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel
