#!/usr/bin/env sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# cursor
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4

bspc config border_width        5
bspc config window_gap          8
bspc config top_padding         0

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

# polkit client
pgrep lxpolkit || lxpolkit &

# ibus daemon
pgrep ibus-daemon || ibus-daemon &

# nm-applet
pgrep -u $USER -x nm-applet > /dev/null || (nm-applet &)

# picom
pgrep -u "$USER" picom >/dev/null || picom -f -b &	

# dunst
pkill dunst
dunst -conf $HOME/.config/dunst/dunstrc &
	
# window swallowing
pgrep bspswallow || bspswallow &

# polybar
pkill polybar
polybar -c $HOME/.config/polybar/launch.sh --pwidgets & 

# rofi/launcher
rofi -no-lazy-grab -show drun -modi drun -theme ~/.config/polybar/shapes/scripts/rofi/launcher.rasi
rofi -no-lazy-grab -show drun -modi drun -show-icons -theme $HOME/ &

# Launch keybinding daemon
sxhkd -conf "$BSPWM_CONFIG/sxhkdrc" &

# xrdb (themes)
xrdb merge $HOME/.Xresources &

# wallpaper
feh --bg-fill $HOME/.config/bspwm/wallpapers/arch.png &

# Autostart
"$BSPWM_CONFIG/autostart" &

# pulseaudio
pulseaudio &

# light-locker
pgrep light-locker || light-locker &

# nitrogen
nitrogen --restore
