#!/usr/bin/env sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

## Bspwm config directory
export BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="$HOME/.config/bspwm/bin:$PATH"

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_SESSION_TYPE="x11"
export XDG_CURRENT_DESKTOP="bspwm"

# wallpapers
export WALLPAPER="$HOME/.config/bspwm/wallpapers/nord_blood.jpg"
export LOCKSCREEN_WALLPAPER="$HOME/.config/bspwm/wallpapers/nord_blood.jpg"

# Parse colors from "${HOME}/.Xresources"
xrdb -load "$HOME/.Xresources"

# autostart
"$HOME/.config/bspwm/bin/autostart.sh" &

#  WINDOW RULES                               
bspc monitor -d 1 2 3 4 


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################
bspc config pointer_modifier          Mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc config top_padding               0
bspc config left_padding              35
bspc config right_padding             0
bspc config bottom_padding            0

# Apply bspwm configurations
bspc config border_width              "$CURRENT_BORDER"
bspc config window_gap                "$CURRENT_GAP"
bspc config split_ratio               0.52

bspc config focused_border_color      "$BLUE" 
bspc config normal_border_color       "$BACKGROUND"
bspc config active_border_color       "$MAGENTA"
bspc config presel_feedback_color     "$GREEN"

bspc config borderless_monocle        true
bspc config gapless_monocle           false
bspc config paddingless_monocle       true
bspc config single_monocle            true
bspc config focus_follows_pointer     true
bspc config center_pseudo_tiled       true

# Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans




###External rules
# Pseudo automatic mode: always splits focused ~window when opening new windowp
bspc config external_rules_command $HOME/.config/bspwm/bin/pseudo_automatic_mode

# Adjust new window: splits biggest windows to keep windows about the same size
bspc config external_rules_command $HOME/.config/bspwm/bin/adjust-new-window
