#!/bin/bash
# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

# This prevents from loading multiple times the same options on reload
bspc rule -r "*"

## Bspwm config directory
export BSPWM_CONFIG="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="$BSPDIR/bin:$PATH"

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

ẞ bspwm
export XDG_SESSION_TYPE="x11"
export XDG_CURRENT_DESKTOP="bspwm"

# autostart
sh "$HOME/.config/bspwm/bin/autostart.sh" &

#  WINDOW RULES                               
bspc monitor -d 1 2 3 4 


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################
bspc config pointer_modifier          Mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc config top_padding               0
bspc config left_padding              35
bspc config right_padding             0
bspc config bottom_padding            0

# Apply bspwm configurations
bspc config border_width              2
bspc config border_radius             12
bspc config window_gap                8
bspc config split_ratio               0.57

bspc config normal_frame_opacity      0.80
bspc config focused_frame_opacity     0.80

bspc config focused_border_color      #44475A 
bspc config normal_border_color       #282A36
bspc config active_border_color       #282A36
bspc config presel_feedback_color     #282A36

bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config paddingless_monocle       false
bspc config single_monocle            false
bspc config focus_follows_pointer     true
bspc config center_pseudo_tiled       true
bspc config adaptative_raise          true 
bspc config history_aware_focus       true

# Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

###External rules
# Pseudo automatic mode: always splits focused ~window when opening new windowp
bspc config external_rules_command $HOME/.config/bspwm/bin/pseudo_automatic_mode

# Adjust new window: splits biggest windows to keep windows about the same size
bspc config external_rules_command $HOME/.config/bspwm/bin/adjust-new-window
